name: app
description: camp2docker test applciation
camp_version: CAMP 1.1
artifacts:
    -
        name: Server file
        artifact_type: Nodejs:Application
        content: { href: app.js}
        requirements:
            -
                requirement_type: Nodejs:Run
                Nodejs.Port: 3000
                fulfillment:
                    id: Nodejs.runtime
                    characteristics:
                        -
                            characteristic_type: Nodejs
            -
                requirement_type: ConnectTo
                dbname: BGA
                smallfiles: true
                fulfillment: id:mongo
    -
        name: MongoDump
        artifact_type: MongoDB:Dump
        content: { href: dump }
        requirements:
            -
                requirement_type: MongoDB:ImportDump
                fulfillment:
                    id: mongo
                    characteristics:
                        -
                            characteristic_type: MongoDB
                            MongoDB:version: latest
